/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.thjava.helloworld.view;


import com.thjava.helloworld.model.Model;
import java.awt.Toolkit;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author Admin
 */
public class View extends javax.swing.JFrame {

    private int xMouse;
    private int yMouse;
//    private int width;
//    private int height;

    public View() {
        initComponents();
//        position();
    }

//    public void position() {
//        width = (Toolkit.getDefaultToolkit().getScreenSize().width / 2) - 185;
//        height = Toolkit.getDefaultToolkit().getScreenSize().height - 500;
//        this.setLocation(width, height);
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBg = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblX = new javax.swing.JLabel();
        lblTextTitle = new javax.swing.JLabel();
        btnEnter = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        txtName5 = new javax.swing.JTextField();
        txtName2 = new javax.swing.JTextField();
        txtName3 = new javax.swing.JTextField();
        txtName4 = new javax.swing.JTextField();
        txtName6 = new javax.swing.JTextField();
        random = new javax.swing.JButton();

        lblBg.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lblBgMouseDragged(evt);
            }
        });
        lblBg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblBgMousePressed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblX.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblX.setForeground(new java.awt.Color(193, 0, 50));
        lblX.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblX.setText("x");
        lblX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblXMouseClicked(evt);
            }
        });
        jPanel1.add(lblX, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 20, -1));

        lblTextTitle.setForeground(new java.awt.Color(104, 30, 126));
        lblTextTitle.setText("Enter your Hashtag:");
        jPanel1.add(lblTextTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 260, -1));

        btnEnter.setBackground(new java.awt.Color(177, 231, 223));
        btnEnter.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnEnter.setForeground(new java.awt.Color(0, 101, 68));
        btnEnter.setText("Enter");
        btnEnter.setBorder(null);
        btnEnter.setFocusPainted(false);
        btnEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterActionPerformed(evt);
            }
        });
        jPanel1.add(btnEnter, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, 80, 40));

        btnClear.setBackground(new java.awt.Color(254, 197, 222));
        btnClear.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnClear.setForeground(new java.awt.Color(193, 0, 50));
        btnClear.setText("Clear");
        btnClear.setBorder(null);
        btnClear.setFocusPainted(false);
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel1.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, 80, 40));

        txtName5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtName5ActionPerformed(evt);
            }
        });
        jPanel1.add(txtName5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 270, 40));

        txtName2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtName2ActionPerformed(evt);
            }
        });
        jPanel1.add(txtName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 270, 40));

        txtName3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtName3ActionPerformed(evt);
            }
        });
        jPanel1.add(txtName3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 270, 40));

        txtName4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtName4ActionPerformed(evt);
            }
        });
        jPanel1.add(txtName4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 270, 40));

        txtName6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtName6ActionPerformed(evt);
            }
        });
        jPanel1.add(txtName6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 270, 40));

        random.setText("Show Account");
        jPanel1.add(random, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 130, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblBgMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBgMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xMouse, y-yMouse);
    }//GEN-LAST:event_lblBgMouseDragged

    private void lblBgMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBgMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_lblBgMousePressed

    private void lblXMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblXMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblXMouseClicked

    private void btnEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEnterActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClearActionPerformed

    private void txtName5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtName5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtName5ActionPerformed

    private void txtName2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtName2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtName2ActionPerformed

    private void txtName3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtName3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtName3ActionPerformed

    private void txtName4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtName4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtName4ActionPerformed

    private void txtName6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtName6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtName6ActionPerformed

    // Getters  
    
    public JButton getBtnClear() {
        return btnClear;
    }

    public JButton getBtnEnter() {
        return btnEnter;
    }

    
    
    // สร้างเมธอดแสดงผลลัพธ์
    public void showResult(String [] acc) {
        txtName2.setText(acc[0]);
        txtName3.setText(acc[1]);
        txtName4.setText(acc[2]);
        txtName5.setText(acc[3]);
        txtName6.setText(acc[4]);
    }

    public JButton getRandom() {
        return random;
    }

    public JTextField getTxtName2() {
        return txtName2;
    }

    public JTextField getTxtName3() {
        return txtName3;
    }

    public JTextField getTxtName4() {
        return txtName4;
    }

    public JTextField getTxtName5() {
        return txtName5;
    }

    public JTextField getTxtName6() {
        return txtName6;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnEnter;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBg;
    private javax.swing.JLabel lblTextTitle;
    private javax.swing.JLabel lblX;
    private javax.swing.JButton random;
    private javax.swing.JTextField txtName2;
    private javax.swing.JTextField txtName3;
    private javax.swing.JTextField txtName4;
    private javax.swing.JTextField txtName5;
    private javax.swing.JTextField txtName6;
    // End of variables declaration//GEN-END:variables

    
}
